// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
import "../styles/input.css";
export const metadata = {
  title: "Chat bot App",
  description: "Generated by DGC",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      //  className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
